### PR TITLE
[RFR] Add overwritePoster docs and update default file level annotations

### PR DESCRIPTION
**Pull request by pascalduez**
Refs: #120

### CODE REVIEW

**Comment by pascalduez** [comment]
Crap, maybe this should be targeted on `develop` ?

**Comment by valeriangalliat** [comment]
Awesome.

If it's an already published fixture, it's okay on `master`, must merge it to `develop` too!

**Comment by pascalduez** [comment]
Nope, it's on core `develop` and unpublished, so I might re-traget this PR.

**Comment by valeriangalliat** [comment]
Would be great yeah. I'm afraid you'll have to close this one and make a new one since GitHub don't support re-targeting a PR (at least last time I checked...)

**Pull request closed without merging**
