### PR TITLE
Update call to action verbiage on homepage

### PR DESCRIPTION
**Pull request by oxocode**
* Updates the CTA verbiage on the homepage above the `Get Started` button.

### CODE REVIEW

**Comment by pascalduez** [comment]
:+1:

**Comment by valeriangalliat** [comment]
Why not, what do you think @HugoGiraudel?

**Comment by pascalduez** [comment]
Last call @HugoGiraudel ? I think it's a good correction.

**Comment by HugoGiraudel** [comment]
:)

**Pull request merged**
